SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder_flat
WHERE LO_ORDERDATE >= 19940101 AND LO_ORDERDATE <= 19940131
  AND LO_DISCOUNT >= 4 AND LO_DISCOUNT <= 6
  AND LO_QUANTITY >= 26 AND LO_QUANTITY <= 35
