SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder_flat
WHERE D_WEEKNUMINYEAR = 6 AND D_YEAR = 1994
  AND LO_DISCOUNT >= 5 AND LO_DISCOUNT <= 7
  AND LO_QUANTITY >= 26 AND LO_QUANTITY <= 35
